name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t yourusername/fastapi-auth-microservice .
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push yourusername/fastapi-auth-microservice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"  # Adjust to your region

    - name: Deploy to AWS ECS
      run: |
        # Pull the Docker image from Docker Hub
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
        docker pull yourusername/fastapi-auth-microservice:latest
        # (Optional) Push image to ECR if you're using ECR for your container registry
        # docker tag yourusername/fastapi-auth-microservice:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/your-ecr-repository:latest
        # docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/your-ecr-repository:latest

        # Deploy to ECS using AWS CLI or update ECS service (use your ECS service name)
        aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
